# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyleRestApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indianbanks',
            name='bank_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='indianbanks',
            name='ifsc',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
